// Code generated by protoc-gen-go.
// source: github.com/micro/go-platform/router/proto/router.proto
// DO NOT EDIT!

/*
Package router is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/go-platform/router/proto/router.proto

It has these top-level messages:
	Stats
	Service
	Node
	Selected
	Endpoint
	Metrics
*/
package router

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Stats struct {
	// service for these stats match
	Service *Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	// client making the requests
	Client *Service `protobuf:"bytes,2,opt,name=client" json:"client,omitempty"`
	// time of the sample
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// duration of the sample
	Duration int64 `protobuf:"varint,4,opt,name=duration" json:"duration,omitempty"`
	// Selected stats
	Selected *Selected `protobuf:"bytes,5,opt,name=selected" json:"selected,omitempty"`
	// Endpoint stats
	Endpoints []*Endpoint `protobuf:"bytes,6,rep,name=endpoints" json:"endpoints,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Stats) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Stats) GetClient() *Service {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *Stats) GetSelected() *Selected {
	if m != nil {
		return m.Selected
	}
	return nil
}

func (m *Stats) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type Service struct {
	Name     string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version  string            `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Nodes    []*Node           `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Service) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Service) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Node struct {
	Id       string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Address  string            `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Port     int64             `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Node) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Selected struct {
	Errors  *Metrics `protobuf:"bytes,7,opt,name=errors" json:"errors,omitempty"`
	Success *Metrics `protobuf:"bytes,5,opt,name=success" json:"success,omitempty"`
	Dropped *Metrics `protobuf:"bytes,6,opt,name=dropped" json:"dropped,omitempty"`
}

func (m *Selected) Reset()                    { *m = Selected{} }
func (m *Selected) String() string            { return proto.CompactTextString(m) }
func (*Selected) ProtoMessage()               {}
func (*Selected) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Selected) GetErrors() *Metrics {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Selected) GetSuccess() *Metrics {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *Selected) GetDropped() *Metrics {
	if m != nil {
		return m.Dropped
	}
	return nil
}

type Endpoint struct {
	// Name of the endpoint
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Success and error rates
	Errors  *Metrics `protobuf:"bytes,2,opt,name=errors" json:"errors,omitempty"`
	Success *Metrics `protobuf:"bytes,3,opt,name=success" json:"success,omitempty"`
	Dropped *Metrics `protobuf:"bytes,4,opt,name=dropped" json:"dropped,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Endpoint) GetErrors() *Metrics {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Endpoint) GetSuccess() *Metrics {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *Endpoint) GetDropped() *Metrics {
	if m != nil {
		return m.Dropped
	}
	return nil
}

type Metrics struct {
	Count   int64   `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Mean    float64 `protobuf:"fixed64,2,opt,name=mean" json:"mean,omitempty"`
	StdDev  float64 `protobuf:"fixed64,3,opt,name=std_dev" json:"std_dev,omitempty"`
	Upper95 float64 `protobuf:"fixed64,4,opt,name=upper95" json:"upper95,omitempty"`
}

func (m *Metrics) Reset()                    { *m = Metrics{} }
func (m *Metrics) String() string            { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()               {}
func (*Metrics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Stats)(nil), "Stats")
	proto.RegisterType((*Service)(nil), "Service")
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*Selected)(nil), "Selected")
	proto.RegisterType((*Endpoint)(nil), "Endpoint")
	proto.RegisterType((*Metrics)(nil), "Metrics")
}

var fileDescriptor0 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x6f, 0xd4, 0x30,
	0x10, 0xc5, 0xe5, 0x64, 0xb3, 0xc9, 0x4e, 0xa9, 0x80, 0x80, 0x90, 0xf9, 0x73, 0xa8, 0x56, 0x42,
	0xea, 0x85, 0x44, 0x02, 0x81, 0x80, 0x7b, 0x25, 0x2e, 0x70, 0xe9, 0x8d, 0x0b, 0x72, 0xed, 0xa1,
	0xb5, 0x58, 0xc7, 0xd1, 0x78, 0xb2, 0x52, 0x3f, 0x02, 0x1f, 0x01, 0x89, 0x0f, 0x8b, 0xe3, 0x64,
	0xa9, 0xba, 0xd5, 0x9e, 0x7a, 0x9c, 0x79, 0xd1, 0x7b, 0xbf, 0xcc, 0x33, 0x7c, 0xb8, 0xb4, 0x7c,
	0x35, 0x5c, 0x34, 0xda, 0xbb, 0xd6, 0x59, 0x4d, 0xbe, 0xbd, 0xf4, 0x6f, 0xfa, 0x8d, 0xe2, 0x9f,
	0x9e, 0x5c, 0x4b, 0x7e, 0x60, 0xa4, 0xb6, 0x27, 0xcf, 0x7e, 0x1e, 0x9a, 0x34, 0xac, 0xff, 0x0a,
	0x28, 0xce, 0x59, 0x71, 0xa8, 0x9f, 0x43, 0x19, 0x90, 0xb6, 0x56, 0xa3, 0x14, 0x27, 0xe2, 0xf4,
	0xe8, 0x6d, 0xd5, 0x9c, 0x4f, 0x73, 0x2d, 0x61, 0xa9, 0x37, 0x16, 0x3b, 0x96, 0xd9, 0x9e, 0xf2,
	0x18, 0x56, 0x6c, 0x1d, 0x06, 0x56, 0xae, 0x97, 0x79, 0x14, 0xf3, 0xfa, 0x11, 0x54, 0x66, 0x20,
	0xc5, 0xd6, 0x77, 0x72, 0x91, 0x36, 0x2f, 0xa1, 0x0a, 0xb8, 0x41, 0xcd, 0x68, 0x64, 0x91, 0x0c,
	0x56, 0xd1, 0x60, 0x5a, 0xd4, 0xaf, 0x60, 0x85, 0x9d, 0xe9, 0xbd, 0xed, 0x38, 0xc8, 0xe5, 0x49,
	0x9e, 0xd4, 0xb3, 0x79, 0xb3, 0xfe, 0x23, 0xa0, 0xdc, 0x65, 0x3d, 0x80, 0x45, 0xa7, 0xdc, 0x44,
	0xb7, 0xaa, 0x1f, 0x42, 0xb9, 0x45, 0x0a, 0x63, 0x4a, 0x96, 0x16, 0x4f, 0xa1, 0xe8, 0xbc, 0xc1,
	0x10, 0x31, 0x46, 0x93, 0xa2, 0xf9, 0x16, 0xa7, 0xfa, 0x14, 0x2a, 0x87, 0xac, 0x8c, 0x62, 0x15,
	0x69, 0x46, 0xe1, 0xd9, 0x0e, 0xbe, 0xf9, 0x3a, 0x0b, 0x67, 0x1d, 0xd3, 0xf5, 0x8b, 0x16, 0x8e,
	0x6f, 0x2d, 0xea, 0x23, 0xc8, 0x7f, 0xe1, 0xf5, 0x1c, 0x77, 0x0c, 0xc5, 0x56, 0x6d, 0x06, 0x9c,
	0xc2, 0x3e, 0x67, 0x1f, 0xc5, 0xfa, 0xb7, 0x80, 0x45, 0xca, 0x00, 0xc8, 0xac, 0xb9, 0xc1, 0x52,
	0xc6, 0x10, 0x86, 0x30, 0x63, 0x45, 0xea, 0xde, 0x13, 0xcf, 0xc7, 0x79, 0x7d, 0x07, 0xe7, 0x49,
	0xe2, 0xbc, 0x2f, 0xcb, 0x77, 0xa8, 0xfe, 0x5f, 0x34, 0xb6, 0x85, 0x44, 0x9e, 0x82, 0x2c, 0xe7,
	0xb6, 0xa2, 0x17, 0x59, 0x3d, 0x55, 0x3c, 0x68, 0x3d, 0xc2, 0x15, 0x77, 0x25, 0x43, 0xbe, 0xef,
	0x63, 0x45, 0xcb, 0xdb, 0xd2, 0xfa, 0x0a, 0xaa, 0x5d, 0x1f, 0x7b, 0x1d, 0xdc, 0x24, 0x65, 0x87,
	0x93, 0xf2, 0xc3, 0x49, 0x8b, 0xbd, 0xa4, 0x2f, 0x50, 0xee, 0xbe, 0x8a, 0xff, 0xa8, 0xfd, 0x10,
	0x5f, 0x9c, 0x48, 0x77, 0x8b, 0xb9, 0x0e, 0xd5, 0x54, 0xb5, 0x18, 0x8f, 0x1c, 0xd8, 0xfc, 0x30,
	0xb8, 0x4d, 0xee, 0x69, 0x31, 0x44, 0x47, 0xfa, 0xf4, 0x3e, 0x79, 0x8a, 0x8b, 0x65, 0x7a, 0xdd,
	0xef, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x78, 0xa8, 0x77, 0xc5, 0x17, 0x03, 0x00, 0x00,
}
