// Code generated by protoc-gen-go.
// source: github.com/micro/go-platform/router/proto/router.proto
// DO NOT EDIT!

/*
Package go_micro_platform_router is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/go-platform/router/proto/router.proto

It has these top-level messages:
	Stats
	Service
	Node
	Endpoint
	Value
	Selected
	EndpointStats
	Metrics
*/
package go_micro_platform_router

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Stats struct {
	// service for these stats match
	Service *Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	// client making the requests
	Client *Service `protobuf:"bytes,2,opt,name=client" json:"client,omitempty"`
	// time of the sample
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// duration of the sample
	Duration int64 `protobuf:"varint,4,opt,name=duration" json:"duration,omitempty"`
	// Selected stats
	Selected *Selected `protobuf:"bytes,5,opt,name=selected" json:"selected,omitempty"`
	// Endpoint stats
	EndpointStats []*EndpointStats `protobuf:"bytes,6,rep,name=endpoint_stats" json:"endpoint_stats,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Stats) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Stats) GetClient() *Service {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *Stats) GetSelected() *Selected {
	if m != nil {
		return m.Selected
	}
	return nil
}

func (m *Stats) GetEndpointStats() []*EndpointStats {
	if m != nil {
		return m.EndpointStats
	}
	return nil
}

type Service struct {
	Name      string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version   string            `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Metadata  map[string]string `protobuf:"bytes,3,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Endpoints []*Endpoint       `protobuf:"bytes,4,rep,name=endpoints" json:"endpoints,omitempty"`
	Nodes     []*Node           `protobuf:"bytes,5,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Service) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Service) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *Service) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Id       string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Address  string            `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Port     int64             `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Node) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Endpoint struct {
	Name     string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Request  *Value            `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Response *Value            `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Endpoint) GetRequest() *Value {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Endpoint) GetResponse() *Value {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Endpoint) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Value struct {
	Name   string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type   string   `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Values []*Value `protobuf:"bytes,3,rep,name=values" json:"values,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Value) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type Selected struct {
	Errors  *Metrics `protobuf:"bytes,7,opt,name=errors" json:"errors,omitempty"`
	Success *Metrics `protobuf:"bytes,5,opt,name=success" json:"success,omitempty"`
	Dropped *Metrics `protobuf:"bytes,6,opt,name=dropped" json:"dropped,omitempty"`
}

func (m *Selected) Reset()                    { *m = Selected{} }
func (m *Selected) String() string            { return proto.CompactTextString(m) }
func (*Selected) ProtoMessage()               {}
func (*Selected) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Selected) GetErrors() *Metrics {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Selected) GetSuccess() *Metrics {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *Selected) GetDropped() *Metrics {
	if m != nil {
		return m.Dropped
	}
	return nil
}

type EndpointStats struct {
	// Name of the endpoint
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Success and error rates
	Errors  *Metrics `protobuf:"bytes,2,opt,name=errors" json:"errors,omitempty"`
	Success *Metrics `protobuf:"bytes,3,opt,name=success" json:"success,omitempty"`
	Dropped *Metrics `protobuf:"bytes,4,opt,name=dropped" json:"dropped,omitempty"`
}

func (m *EndpointStats) Reset()                    { *m = EndpointStats{} }
func (m *EndpointStats) String() string            { return proto.CompactTextString(m) }
func (*EndpointStats) ProtoMessage()               {}
func (*EndpointStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *EndpointStats) GetErrors() *Metrics {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *EndpointStats) GetSuccess() *Metrics {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *EndpointStats) GetDropped() *Metrics {
	if m != nil {
		return m.Dropped
	}
	return nil
}

type Metrics struct {
	Count   int64   `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Mean    float64 `protobuf:"fixed64,2,opt,name=mean" json:"mean,omitempty"`
	StdDev  float64 `protobuf:"fixed64,3,opt,name=std_dev" json:"std_dev,omitempty"`
	Upper95 float64 `protobuf:"fixed64,4,opt,name=upper95" json:"upper95,omitempty"`
}

func (m *Metrics) Reset()                    { *m = Metrics{} }
func (m *Metrics) String() string            { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()               {}
func (*Metrics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*Stats)(nil), "go.micro.platform.router.Stats")
	proto.RegisterType((*Service)(nil), "go.micro.platform.router.Service")
	proto.RegisterType((*Node)(nil), "go.micro.platform.router.Node")
	proto.RegisterType((*Endpoint)(nil), "go.micro.platform.router.Endpoint")
	proto.RegisterType((*Value)(nil), "go.micro.platform.router.Value")
	proto.RegisterType((*Selected)(nil), "go.micro.platform.router.Selected")
	proto.RegisterType((*EndpointStats)(nil), "go.micro.platform.router.EndpointStats")
	proto.RegisterType((*Metrics)(nil), "go.micro.platform.router.Metrics")
}

var fileDescriptor0 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x94, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x95, 0x64, 0xb3, 0xc9, 0x4e, 0x59, 0xfe, 0xf8, 0x14, 0x71, 0x80, 0x92, 0x0b, 0x1c,
	0x68, 0x52, 0x0a, 0x45, 0xc0, 0x01, 0x04, 0x52, 0x25, 0x2e, 0x70, 0x29, 0xe2, 0x5a, 0xb9, 0xf1,
	0xb0, 0x44, 0x6c, 0xe2, 0x60, 0x3b, 0x2b, 0xed, 0x95, 0x23, 0x8f, 0x81, 0xc4, 0x3b, 0xf0, 0x5c,
	0x3c, 0x01, 0x13, 0x27, 0x69, 0x09, 0x68, 0xff, 0xb4, 0x3d, 0xc6, 0x99, 0xcf, 0xfe, 0x7e, 0x9f,
	0x67, 0x0c, 0x4f, 0x67, 0xb9, 0xf9, 0x5c, 0x9f, 0x26, 0x99, 0x2c, 0xd2, 0x22, 0xcf, 0x94, 0x4c,
	0x67, 0x72, 0xaf, 0x9a, 0x73, 0xf3, 0x49, 0xaa, 0x22, 0x55, 0xb2, 0x36, 0xa8, 0xd2, 0x4a, 0x49,
	0x23, 0xbb, 0x8f, 0xc4, 0x7e, 0xb0, 0x68, 0x26, 0x13, 0x5b, 0x9f, 0xf4, 0xc5, 0x49, 0xfb, 0x3f,
	0xfe, 0xee, 0x82, 0x7f, 0x6c, 0xb8, 0xd1, 0xec, 0x00, 0x02, 0x8d, 0x6a, 0x91, 0x67, 0x18, 0x39,
	0xbb, 0xce, 0x83, 0x9d, 0x83, 0x7b, 0xc9, 0x2a, 0x55, 0x72, 0xdc, 0x16, 0xb2, 0x47, 0x30, 0xce,
	0xe6, 0x39, 0x96, 0x26, 0x72, 0xb7, 0x95, 0xdc, 0x82, 0x89, 0xc9, 0x0b, 0xd4, 0x86, 0x17, 0x55,
	0xe4, 0x91, 0xca, 0x63, 0x37, 0x21, 0x14, 0xb5, 0xe2, 0x26, 0x97, 0x65, 0x34, 0xb2, 0x2b, 0x4f,
	0x20, 0xd4, 0x38, 0xc7, 0xcc, 0xa0, 0x88, 0x7c, 0xbb, 0x73, 0xbc, 0x6e, 0xe7, 0xb6, 0x92, 0xbd,
	0x82, 0xeb, 0x58, 0x8a, 0x4a, 0xe6, 0xa5, 0x39, 0xd1, 0x0d, 0x53, 0x34, 0xde, 0xf5, 0x48, 0x7b,
	0x7f, 0xb5, 0xf6, 0xa8, 0xab, 0xb7, 0x11, 0xc4, 0xdf, 0x5c, 0x08, 0x7a, 0x9f, 0xd7, 0x60, 0x54,
	0xf2, 0xa2, 0xcd, 0x62, 0xc2, 0x6e, 0x40, 0xb0, 0x40, 0xa5, 0x1b, 0x87, 0xae, 0x5d, 0x78, 0x0d,
	0x61, 0x81, 0x86, 0x0b, 0x6e, 0x38, 0x51, 0x34, 0xa7, 0xa4, 0x1b, 0xd9, 0x93, 0x77, 0x9d, 0xe2,
	0xa8, 0x34, 0x6a, 0xc9, 0x0e, 0x61, 0xd2, 0xdb, 0xd5, 0xc4, 0xed, 0xad, 0xa7, 0xec, 0x9d, 0xb2,
	0x3d, 0xf0, 0x4b, 0x29, 0x50, 0x53, 0x30, 0x8d, 0xe4, 0xce, 0x6a, 0xc9, 0x7b, 0x2a, 0xbb, 0x9d,
	0xc2, 0x74, 0x78, 0xec, 0x0e, 0x78, 0x5f, 0x70, 0xd9, 0x71, 0x4d, 0xc1, 0x5f, 0xf0, 0x79, 0x8d,
	0x2d, 0xd5, 0x0b, 0xf7, 0x99, 0x13, 0xff, 0x70, 0x60, 0xd4, 0x28, 0x19, 0x80, 0x9b, 0x8b, 0x73,
	0x7e, 0x2e, 0x84, 0x42, 0xad, 0x3b, 0x7e, 0x8a, 0xa7, 0x92, 0xca, 0x74, 0x37, 0xf8, 0xf2, 0xaf,
	0x34, 0x5a, 0x92, 0x87, 0xeb, 0x6d, 0x0d, 0xa3, 0xb8, 0xb8, 0xc9, 0xdf, 0x0e, 0x84, 0x67, 0x89,
	0x0c, 0xaf, 0x6a, 0x1f, 0x02, 0x85, 0x5f, 0x6b, 0xea, 0xb0, 0xae, 0x29, 0xef, 0xae, 0xb6, 0xf2,
	0xb1, 0xd9, 0x96, 0xba, 0x38, 0x24, 0xb2, 0x4a, 0x96, 0x1a, 0x2d, 0xcf, 0x16, 0x92, 0x37, 0xff,
	0x01, 0xef, 0x6f, 0xbe, 0xba, 0xab, 0x42, 0x7f, 0x00, 0xbf, 0x3d, 0x7d, 0x08, 0x4c, 0x5f, 0x66,
	0x59, 0x75, 0x85, 0x2c, 0x85, 0xb1, 0xd5, 0xe9, 0xae, 0x2d, 0x37, 0xa1, 0xc4, 0x3f, 0x29, 0xca,
	0xb3, 0x11, 0xa2, 0x81, 0x46, 0xa5, 0xa4, 0xd2, 0x51, 0xb0, 0x69, 0xa0, 0xc9, 0xbb, 0xca, 0xb3,
	0xf6, 0xdd, 0xa8, 0xb3, 0xac, 0x69, 0x0d, 0xff, 0x02, 0x1a, 0xa1, 0x64, 0x55, 0xd1, 0x78, 0x8f,
	0xb7, 0xd4, 0xc4, 0xbf, 0x1c, 0x98, 0x0e, 0xc6, 0xf5, 0x9f, 0x18, 0xce, 0xad, 0xbb, 0x97, 0xb0,
	0xee, 0x5d, 0xc2, 0xfa, 0x68, 0x5b, 0xeb, 0x6f, 0x21, 0xe8, 0xe5, 0x74, 0xad, 0x99, 0xac, 0xe9,
	0xc1, 0x74, 0xec, 0xe0, 0x10, 0x42, 0x81, 0xbc, 0x7d, 0x54, 0x9c, 0x66, 0xca, 0xb4, 0x11, 0x27,
	0x02, 0x17, 0xd6, 0x8f, 0x5d, 0xa8, 0xe9, 0x28, 0xf5, 0xfc, 0xd0, 0x1e, 0xe6, 0x9c, 0x8e, 0xed,
	0x7b, 0xfe, 0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x9a, 0xce, 0x8f, 0x09, 0x06, 0x00,
	0x00,
}
